### ISSUE TITLE
Add support for sub config on packages

### ISSUE THREAD

**Issue by tossmilestone** [stevvooe/protobuild#2] opened 2017-07-21 07:00 UTC
Protobuild is really a good tool to build protobufs. But when we want to config specific options in one package, there is no way to do that. Because protobuild only support a global config file in the project root.

Support a sub config file inherited from the global config file would be a good solution.

I will appreciate if this feature is added.

**Comment by stevvooe** [comment] 2017-07-21 19:51
Could you give an example where a single project has vastly different configurations?

**Comment by stevvooe** [comment] 2017-07-21 21:18
@tossmilestone Took a closer look here in context of https://github.com/docker/swarmkit/issues/2311 and it seems the problem is the `deepcopy` plugin. We'll have to make that plugin get controller by a directive per type. The current behavior is a little pathological, so we should fix that before introducing more features to protobuild.

The main problem here is that we could do something like this:

```
pkg1/Protobuild.toml
pkg2/Protobuild.toml
```

However, in the case of swarmkit, we have two invocations of protoc in the same package. One invocation has `deepcopy` enabled and another does not. We'd have to introduce syntax into protobuild to control multiple invocations with different parameters.

The goal of protobuild is to ensure we always do a single invocation, so the packages are created as a proper unit. Thus, I think fixing the problems in swarmkit start with fixing the deepcopy plugin to take a directive, rather than automatically generating `Copy()` for every type.

**Comment by tossmilestone** [comment] 2017-07-22 03:26
@stevvooe Thanks for your reply, I will have a try to fix the swarmkit problems.

**Comment by stevvooe** [comment] 2017-08-04 22:18
@tossmilestone Looks like we are going forward with swarmkit, but checkout the changes in #6 for how we might add per package generation directives.

**Comment by tossmilestone** [comment] 2017-08-05 05:08
@stevvooe It's really a great work. I'll look to use it in swarmkit.

**Comment by stevvooe** [comment] 2017-08-07 22:49
@tossmilestone Ok, closing this issue, then.

**Closed by stevvooe** 2017-08-07 22:49 UTC
